'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronDown, Crosshair, Globe2, Hammer, Mail, MapPin, Phone, ShieldCheck, UserRound, UsersRound } from 'lucide-react'

const languages = [
  ['English', 'English'], ['हिंदी', 'Hindi'], ['বাংলা', 'Bengali'], ['मराठी', 'Marathi'],
  ['తెలుగు', 'Telugu'], ['தமிழ்', 'Tamil'], ['ગુજરાતી', 'Gujarati'], ['ಕನ್ನಡ', 'Kannada'],
]

const roles = [
  { id: 'HIRER', title: 'Hire a worker', description: 'Find trusted help for your home or business.', icon: UsersRound },
  { id: 'WORKER', title: 'Work as a provider', description: 'Find nearby jobs and grow your work.', icon: Hammer },
  { id: 'BOTH', title: 'Both', description: 'Hire help and find work from one account.', icon: ShieldCheck },
]

const copy = {
  English: { step: 'Step', of: 'of', continue: 'Continue', finish: 'Finish setup', welcome: 'Welcome to Labzeck', language: 'Select your language', languageDescription: 'Choose one preferred language for your Labzeck experience.', search: 'Search languages', setupReady: 'Your profile is ready.', go: 'Go to Labzeck', privacy: 'Your information is private and only used to personalize your experience.' },
  Hindi: { step: 'चरण', of: 'में से', continue: 'जारी रखें', finish: 'सेटअप पूरा करें', welcome: 'Labzeck में आपका स्वागत है', language: 'अपनी भाषा चुनें', languageDescription: 'Labzeck इस्तेमाल करने के लिए अपनी पसंदीदा भाषा चुनें।', search: 'भाषा खोजें', setupReady: 'आपकी प्रोफ़ाइल तैयार है।', go: 'Labzeck पर जाएं', privacy: 'आपकी जानकारी निजी है और केवल अनुभव को बेहतर बनाने के लिए इस्तेमाल होती है।' },
  Bengali: { step: 'ধাপ', of: 'এর মধ্যে', continue: 'চালিয়ে যান', finish: 'সেটআপ সম্পূর্ণ করুন', welcome: 'Labzeck-এ স্বাগতম', language: 'আপনার ভাষা বেছে নিন', languageDescription: 'Labzeck ব্যবহারের জন্য আপনার পছন্দের ভাষা বেছে নিন।', search: 'ভাষা খুঁজুন', setupReady: 'আপনার প্রোফাইল প্রস্তুত।', go: 'Labzeck-এ যান', privacy: 'আপনার তথ্য ব্যক্তিগত এবং অভিজ্ঞতা উন্নত করতে ব্যবহার করা হয়।' },
  Marathi: { step: 'पायरी', of: 'पैकी', continue: 'पुढे चला', finish: 'सेटअप पूर्ण करा', welcome: 'Labzeck मध्ये स्वागत आहे', language: 'तुमची भाषा निवडा', languageDescription: 'Labzeck साठी तुमची पसंतीची भाषा निवडा.', search: 'भाषा शोधा', setupReady: 'तुमचे प्रोफाइल तयार आहे.', go: 'Labzeck वर जा', privacy: 'तुमची माहिती खाजगी आहे आणि अनुभव सुधारण्यासाठी वापरली जाते.' },
  Telugu: { step: 'దశ', of: 'లో', continue: 'కొనసాగించండి', finish: 'సెటప్ పూర్తి చేయండి', welcome: 'Labzeckకు స్వాగతం', language: 'మీ భాషను ఎంచుకోండి', languageDescription: 'Labzeck అనుభవం కోసం మీ భాషను ఎంచుకోండి.', search: 'భాషలను వెతకండి', setupReady: 'మీ ప్రొఫైల్ సిద్ధంగా ఉంది.', go: 'Labzeckకు వెళ్లండి', privacy: 'మీ సమాచారం ప్రైవేట్‌గా ఉంటుంది.' },
  Tamil: { step: 'படி', of: 'இல்', continue: 'தொடரவும்', finish: 'அமைப்பை முடிக்கவும்', welcome: 'Labzeck-க்கு வரவேற்கிறோம்', language: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்', languageDescription: 'Labzeck அனுபவத்திற்கான மொழியைத் தேர்ந்தெடுக்கவும்.', search: 'மொழிகளைத் தேடுங்கள்', setupReady: 'உங்கள் சுயவிவரம் தயாராக உள்ளது.', go: 'Labzeck செல்லுங்கள்', privacy: 'உங்கள் தகவல் தனிப்பட்டது.' },
  Gujarati: { step: 'પગલું', of: 'માંથી', continue: 'ચાલુ રાખો', finish: 'સેટઅપ પૂર્ણ કરો', welcome: 'Labzeckમાં સ્વાગત છે', language: 'તમારી ભાષા પસંદ કરો', languageDescription: 'Labzeck માટે તમારી પસંદગીની ભાષા પસંદ કરો.', search: 'ભાષા શોધો', setupReady: 'તમારી પ્રોફાઇલ તૈયાર છે.', go: 'Labzeck પર જાઓ', privacy: 'તમારી માહિતી ખાનગી છે.' },
  Kannada: { step: 'ಹಂತ', of: 'ರಲ್ಲಿ', continue: 'ಮುಂದುವರಿಸಿ', finish: 'ಸೆಟಪ್ ಪೂರ್ಣಗೊಳಿಸಿ', welcome: 'Labzeck ಗೆ ಸ್ವಾಗತ', language: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ', languageDescription: 'Labzeck ಅನುಭವಕ್ಕಾಗಿ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.', search: 'ಭಾಷೆಗಳನ್ನು ಹುಡುಕಿ', setupReady: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಸಿದ್ಧವಾಗಿದೆ.', go: 'Labzeck ಗೆ ಹೋಗಿ', privacy: 'ನಿಮ್ಮ ಮಾಹಿತಿ ಖಾಸಗಿಯಾಗಿದೆ.' },
} as const

type LanguageKey = keyof typeof copy
function getCopy(language: string) { return copy[language as LanguageKey] ?? copy.English }

export function OnboardingFlow() {
  const [step, setStep] = useState(0)
  const [location, setLocation] = useState('')
  const [language, setLanguage] = useState('English')
  const [role, setRole] = useState('WORKER')
  const [auth, setAuth] = useState('email')
  const [name, setName] = useState('')
  const [phone, setPhone] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [occupation, setOccupation] = useState('Plumber')
  const [done, setDone] = useState(false)
  const progress = Math.round((step / 6) * 100)
  const ui = getCopy(language)
  const canContinue = step === 1 ? location.trim().length > 2 : step === 2 ? !!language : step === 3 ? !!auth && name.trim().length > 1 && phone.replace(/\D/g, '').length >= 10 && email.includes('@') && password.length >= 8 : step === 4 ? !!role : step === 5 ? name.trim().length > 1 : true
  const stepTitles = ['Welcome to Labzeck', 'Where are you located?', 'Select your language', 'Create your account', 'How will you use Labzeck?', 'Tell us about you', 'You are all set']

  const next = () => { if (!canContinue) return; if (step === 6) setDone(true); else setStep((current) => current + 1) }
  const back = () => setStep((current) => Math.max(0, current - 1))

  if (done) return <main className="flex min-h-screen items-center justify-center bg-muted px-5"><div className="w-full max-w-md rounded-[2rem] bg-card p-8 text-center shadow-xl"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-primary text-primary-foreground"><Check className="size-8" /></div><h1 className="mt-6 text-2xl font-bold">{ui.welcome}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{ui.setupReady} {role === 'WORKER' ? (language === 'Hindi' ? 'आपको पास में काम के अवसर दिखेंगे।' : "We'll show you trusted work opportunities nearby.") : (language === 'Hindi' ? 'आपको पास में भरोसेमंद कामगार दिखेंगे।' : "We&apos;ll show you trusted workers nearby.")}</p><button onClick={() => window.location.reload()} className="mt-8 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-primary py-3.5 text-sm font-bold text-primary-foreground">{ui.go} <ArrowRight className="size-4" /></button></div></main>

  return <main className="min-h-screen bg-muted px-0 text-foreground md:flex md:items-center md:justify-center md:px-6 md:py-8"><section className="relative flex min-h-screen w-full max-w-md flex-col overflow-hidden bg-card shadow-2xl shadow-primary/10 md:min-h-[820px] md:rounded-[2rem] md:border md:border-border/60"><div className="pointer-events-none absolute inset-x-0 top-0 h-1 bg-primary" /><header className="sticky top-0 z-10 flex items-center gap-3 border-b border-border/60 bg-card/95 px-4 pb-4 pt-5 backdrop-blur-sm"><button onClick={back} disabled={step === 0} className="flex size-10 shrink-0 items-center justify-center rounded-2xl border border-border/70 bg-background text-muted-foreground transition-colors hover:border-primary hover:text-primary disabled:invisible" aria-label="Go back"><ArrowLeft className="size-5" /></button><div className="flex-1"><div className="flex items-center justify-between text-xs font-semibold text-muted-foreground"><span>{ui.step} {step + 1} {ui.of} 7</span><span>{progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.max(progress, 8)}%` }} /></div></div><div className="size-9" /></header><div className="flex flex-1 flex-col px-6 pb-6 pt-8"><div className="flex-1">{step === 0 && <Welcome />}{step === 1 && <LocationStep value={location} onChange={setLocation} />}{step === 2 && <LanguageStep value={language} onChange={setLanguage} />}{step === 3 && <AuthStep value={auth} onChange={setAuth} name={name} phone={phone} email={email} password={password} onNameChange={setName} onPhoneChange={setPhone} onEmailChange={setEmail} onPasswordChange={setPassword} />}{step === 4 && <RoleStep value={role} onChange={setRole} />}{step === 5 && <ProfileStep name={name} onNameChange={setName} occupation={occupation} onOccupationChange={setOccupation} />}{step === 6 && <ReviewStep location={location} language={language} role={role} name={name} />}</div><button onClick={next} disabled={!canContinue} className="mt-8 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-primary py-3.5 text-sm font-bold text-primary-foreground shadow-lg shadow-primary/20 transition-all hover:-translate-y-0.5 hover:shadow-xl disabled:cursor-not-allowed disabled:opacity-40">{step === 6 ? ui.finish : ui.continue} <ArrowRight className="size-4" /></button>{step === 0 && <p className="mt-4 text-center text-xs text-muted-foreground">Already have an account? <button className="font-bold text-primary">Log in</button></p>}</div></section></main>
}

function Welcome() { return <div className="flex h-full flex-col items-center justify-center text-center"><div className="flex size-24 items-center justify-center rounded-3xl bg-primary/10 text-primary"><UsersRound className="size-12" /></div><p className="mt-8 text-xs font-bold uppercase tracking-[0.2em] text-primary">Simple work. Better together.</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-balance">Connect with trusted local people.</h1><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">Find reliable workers, discover nearby jobs, and build your work profile with Labzeck.</p></div> }
function StepHeading({ icon: Icon, title, description }: { icon: typeof MapPin; title: string; description: string }) { return <div><div className="flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Icon className="size-6" /></div><h1 className="mt-6 text-3xl font-bold tracking-tight text-balance">{title}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div> }
function LocationStep({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <div><StepHeading icon={MapPin} title="Where are you located?" description="We&apos;ll use your location to show relevant work and workers nearby." /><button onClick={() => onChange('New Delhi')} className="mt-8 flex min-h-16 w-full items-center gap-3 rounded-2xl border border-primary/30 bg-primary/5 p-4 text-left transition-all hover:-translate-y-0.5 hover:border-primary hover:shadow-md"><Crosshair className="size-5 text-primary" /><span><strong className="block text-sm">Use current location</strong><small className="text-xs text-muted-foreground">Fast and more relevant results</small></span></button><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border" />or<span className="h-px flex-1 bg-border" /></div><label className="flex flex-col gap-2 text-sm font-semibold">Enter city, area or pincode<input value={value} onChange={(event) => onChange(event.target.value)} placeholder="e.g. Dwarka, New Delhi" className="min-h-12 rounded-2xl border border-border/80 bg-background px-4 py-3 font-normal outline-none transition-all placeholder:text-muted-foreground/70 focus:border-primary focus:bg-card focus:shadow-md focus:shadow-primary/10" /></label></div> }
function LanguageStep({ value, onChange }: { value: string; onChange: (value: string) => void }) { const [query, setQuery] = useState(''); const filtered = useMemo(() => languages.filter(([native, english]) => `${native} ${english}`.toLowerCase().includes(query.toLowerCase())), [query]); const ui = getCopy(value); return <div><StepHeading icon={Globe2} title={ui.language} description={ui.languageDescription} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={ui.search} aria-label={ui.search} className="mt-6 min-h-12 w-full rounded-2xl border border-border bg-background px-4 py-3 text-sm outline-none transition-colors focus:border-primary focus:bg-card" /><div className="mt-4 grid grid-cols-2 gap-3">{filtered.map(([native, english]) => <button key={english} onClick={() => onChange(english)} className={`flex items-center justify-between rounded-xl border p-3 text-left ${value === english ? 'border-primary bg-primary/10 shadow-md shadow-primary/10' : 'border-border/70 bg-background hover:border-primary/50 hover:bg-primary/5'}`}><span><strong className="block text-sm">{native}</strong><small className="text-xs text-muted-foreground">{english}</small></span>{value === english && <Check className="size-4 text-primary" />}</button>)}</div></div> }
function AuthStep({ value, onChange, name, phone, email, password, onNameChange, onPhoneChange, onEmailChange, onPasswordChange }: { value: string; onChange: (value: string) => void; name: string; phone: string; email: string; password: string; onNameChange: (value: string) => void; onPhoneChange: (value: string) => void; onEmailChange: (value: string) => void; onPasswordChange: (value: string) => void }) { return <div className="rounded-[2rem] border border-border/70 bg-card px-1 py-2"><div className="flex flex-col items-center text-center"><div className="flex size-12 items-center justify-center rounded-2xl bg-primary text-primary-foreground shadow-lg shadow-primary/20"><ShieldCheck className="size-6" /></div><h1 className="mt-4 text-[22px] font-bold tracking-tight">Create your account</h1><p className="mt-2 text-xs leading-5 text-muted-foreground">Enter all details to unlock your Labzeck home</p></div><div className="mt-7 flex flex-col gap-3"><button type="button" onClick={() => onChange('google')} className={`flex min-h-12 items-center gap-4 rounded-xl border px-4 text-left text-xs font-semibold transition-colors ${value === 'google' ? 'border-primary bg-primary/5' : 'border-border/80 bg-card hover:border-primary'}`}><span className="text-lg font-black text-[#4285F4]">G</span><span className="flex-1 text-center">Continue with Google</span></button><div className="grid gap-3"><label className="text-xs font-semibold">Full name<input value={name} onChange={(event) => onNameChange(event.target.value)} required placeholder="Your full name" className="mt-1 min-h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" /></label><label className="text-xs font-semibold">Phone number<input value={phone} onChange={(event) => onPhoneChange(event.target.value)} required type="tel" inputMode="tel" placeholder="10-digit phone number" className="mt-1 min-h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" /></label><label className="text-xs font-semibold">Email address<input value={email} onChange={(event) => onEmailChange(event.target.value)} required type="email" placeholder="you@example.com" className="mt-1 min-h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" /></label><label className="text-xs font-semibold">Password<input value={password} onChange={(event) => onPasswordChange(event.target.value)} required minLength={8} type="password" placeholder="At least 8 characters" className="mt-1 min-h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" /></label></div></div><p className="mt-5 text-center text-[10px] leading-4 text-muted-foreground">Your account details are required before opening the home page.</p></div> }
function RoleStep({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <div><StepHeading icon={UserRound} title="How will you use Labzeck?" description="You can change this later from your profile." /><div className="mt-8 flex flex-col gap-3">{roles.map(({ id, title, description, icon: Icon }) => <button key={id} onClick={() => onChange(id)} className={`flex items-center gap-4 rounded-2xl border p-4 text-left ${value === id ? 'border-primary bg-primary/5' : 'border-border'}`}><div className="flex size-11 items-center justify-center rounded-xl bg-muted text-primary"><Icon className="size-5" /></div><span className="flex-1"><strong className="block text-sm">{title}</strong><small className="mt-1 block text-xs leading-5 text-muted-foreground">{description}</small></span>{value === id && <Check className="size-5 text-primary" />}</button>)}</div></div> }
function ProfileStep({ name, onNameChange, occupation, onOccupationChange }: { name: string; onNameChange: (value: string) => void; occupation: string; onOccupationChange: (value: string) => void }) { return <div><StepHeading icon={UserRound} title="Tell us about you" description="A few details help people find the right match." /><div className="mt-8 flex flex-col gap-4"><label className="flex flex-col gap-2 text-sm font-semibold">Full name<input value={name} onChange={(event) => onNameChange(event.target.value)} placeholder="Your name" className="min-h-12 rounded-2xl border border-border/80 bg-background px-4 py-3 font-normal outline-none transition-all placeholder:text-muted-foreground/70 focus:border-primary focus:bg-card focus:shadow-md focus:shadow-primary/10" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Primary occupation<select value={occupation} onChange={(event) => onOccupationChange(event.target.value)} className="min-h-12 rounded-2xl border border-border/80 bg-background px-4 py-3 font-normal outline-none transition-all placeholder:text-muted-foreground/70 focus:border-primary focus:bg-card focus:shadow-md focus:shadow-primary/10"><option>Plumber</option><option>Electrician</option><option>Painter</option><option>Carpenter</option><option>Cleaner</option><option>Driver</option><option>Mason</option></select></label><label className="flex flex-col gap-2 text-sm font-semibold">Experience<select className="min-h-12 rounded-2xl border border-border/80 bg-background px-4 py-3 font-normal outline-none transition-all placeholder:text-muted-foreground/70 focus:border-primary focus:bg-card focus:shadow-md focus:shadow-primary/10"><option>0–1 years</option><option>1–3 years</option><option>3–5 years</option><option>5+ years</option></select></label></div></div> }
function ReviewStep({ location, language, role, name }: { location: string; language: string; role: string; name: string }) { return <div><StepHeading icon={Check} title="Review your setup" description="Everything looks good. You can update these details anytime." /><div className="mt-8 flex flex-col gap-3 rounded-2xl bg-muted p-4 text-sm"><Row label="Name" value={name || 'Your profile'} /><Row label="Location" value={location} /><Row label="Language" value={language} /><Row label="Using Labzeck to" value={role === 'WORKER' ? 'Find work' : role === 'HIRER' ? 'Hire workers' : 'Hire and work'} /></div><div className="mt-5 flex items-start gap-3 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" />Your information is private and only used to personalize your experience.</div></div> }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 border-b border-border/70 py-2 last:border-0"><span className="text-muted-foreground">{label}</span><strong className="text-right">{value}</strong></div> }

export default OnboardingFlow
